/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResponsibleAiRouteImport } from './routes/responsible-ai'
import { Route as SanatanRouteImport } from './routes/sanatan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WorkspaceRouteRouteImport } from './routes/workspace/route'
import { Route as ApiChatStreamRouteImport } from './routes/api/chat-stream'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as WorkspaceChatRouteImport } from './routes/workspace/chat'
import { Route as WorkspaceImageRouteImport } from './routes/workspace/image'
import { Route as WorkspaceLibraryRouteImport } from './routes/workspace/library'
import { Route as WorkspaceOverviewRouteImport } from './routes/workspace/overview'
import { Route as WorkspaceResearchRouteImport } from './routes/workspace/research'
import { Route as WorkspaceSanatanRouteImport } from './routes/workspace/sanatan'
import { Route as WorkspaceSettingsRouteImport } from './routes/workspace/settings'
import { Route as WorkspaceVideoRouteImport } from './routes/workspace/video'
import { Route as WorkspaceVoiceRouteImport } from './routes/workspace/voice'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiPublicVideoFileRouteImport } from './routes/api/public/video-file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleAiRoute = ResponsibleAiRouteImport.update({
  id: '/responsible-ai',
  path: '/responsible-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const SanatanRoute = SanatanRouteImport.update({
  id: '/sanatan',
  path: '/sanatan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/api/chat-stream',
  path: '/api/chat-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceChatRoute = WorkspaceChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceImageRoute = WorkspaceImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceLibraryRoute = WorkspaceLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceOverviewRoute = WorkspaceOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceResearchRoute = WorkspaceResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSanatanRoute = WorkspaceSanatanRouteImport.update({
  id: '/sanatan',
  path: '/sanatan',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceVideoRoute = WorkspaceVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceVoiceRoute = WorkspaceVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVideoFileRoute = ApiPublicVideoFileRouteImport.update({
  id: '/api/public/video-file',
  path: '/api/public/video-file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/pricing': typeof PricingRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/sanatan': typeof SanatanRoute
  '/settings': typeof SettingsRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/workspace/chat': typeof WorkspaceChatRoute
  '/workspace/image': typeof WorkspaceImageRoute
  '/workspace/library': typeof WorkspaceLibraryRoute
  '/workspace/overview': typeof WorkspaceOverviewRoute
  '/workspace/research': typeof WorkspaceResearchRoute
  '/workspace/sanatan': typeof WorkspaceSanatanRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/video': typeof WorkspaceVideoRoute
  '/workspace/voice': typeof WorkspaceVoiceRoute
  '/auth/': typeof AuthIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/video-file': typeof ApiPublicVideoFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/pricing': typeof PricingRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/sanatan': typeof SanatanRoute
  '/settings': typeof SettingsRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/workspace/chat': typeof WorkspaceChatRoute
  '/workspace/image': typeof WorkspaceImageRoute
  '/workspace/library': typeof WorkspaceLibraryRoute
  '/workspace/overview': typeof WorkspaceOverviewRoute
  '/workspace/research': typeof WorkspaceResearchRoute
  '/workspace/sanatan': typeof WorkspaceSanatanRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/video': typeof WorkspaceVideoRoute
  '/workspace/voice': typeof WorkspaceVoiceRoute
  '/auth': typeof AuthIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/video-file': typeof ApiPublicVideoFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/pricing': typeof PricingRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/sanatan': typeof SanatanRoute
  '/settings': typeof SettingsRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/workspace/chat': typeof WorkspaceChatRoute
  '/workspace/image': typeof WorkspaceImageRoute
  '/workspace/library': typeof WorkspaceLibraryRoute
  '/workspace/overview': typeof WorkspaceOverviewRoute
  '/workspace/research': typeof WorkspaceResearchRoute
  '/workspace/sanatan': typeof WorkspaceSanatanRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/video': typeof WorkspaceVideoRoute
  '/workspace/voice': typeof WorkspaceVoiceRoute
  '/auth/': typeof AuthIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/video-file': typeof ApiPublicVideoFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspace'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/library'
    | '/pricing'
    | '/responsible-ai'
    | '/sanatan'
    | '/settings'
    | '/api/chat-stream'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/workspace/chat'
    | '/workspace/image'
    | '/workspace/library'
    | '/workspace/overview'
    | '/workspace/research'
    | '/workspace/sanatan'
    | '/workspace/settings'
    | '/workspace/video'
    | '/workspace/voice'
    | '/auth/'
    | '/workspace/'
    | '/api/public/chat'
    | '/api/public/razorpay-webhook'
    | '/api/public/video-file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/library'
    | '/pricing'
    | '/responsible-ai'
    | '/sanatan'
    | '/settings'
    | '/api/chat-stream'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/workspace/chat'
    | '/workspace/image'
    | '/workspace/library'
    | '/workspace/overview'
    | '/workspace/research'
    | '/workspace/sanatan'
    | '/workspace/settings'
    | '/workspace/video'
    | '/workspace/voice'
    | '/auth'
    | '/workspace'
    | '/api/public/chat'
    | '/api/public/razorpay-webhook'
    | '/api/public/video-file'
  id:
    | '__root__'
    | '/'
    | '/workspace'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/library'
    | '/pricing'
    | '/responsible-ai'
    | '/sanatan'
    | '/settings'
    | '/api/chat-stream'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/workspace/chat'
    | '/workspace/image'
    | '/workspace/library'
    | '/workspace/overview'
    | '/workspace/research'
    | '/workspace/sanatan'
    | '/workspace/settings'
    | '/workspace/video'
    | '/workspace/voice'
    | '/auth/'
    | '/workspace/'
    | '/api/public/chat'
    | '/api/public/razorpay-webhook'
    | '/api/public/video-file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  LibraryRoute: typeof LibraryRoute
  PricingRoute: typeof PricingRoute
  ResponsibleAiRoute: typeof ResponsibleAiRoute
  SanatanRoute: typeof SanatanRoute
  SettingsRoute: typeof SettingsRoute
  ApiChatStreamRoute: typeof ApiChatStreamRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiPublicVideoFileRoute: typeof ApiPublicVideoFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-ai': {
      id: '/responsible-ai'
      path: '/responsible-ai'
      fullPath: '/responsible-ai'
      preLoaderRoute: typeof ResponsibleAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanatan': {
      id: '/sanatan'
      path: '/sanatan'
      fullPath: '/sanatan'
      preLoaderRoute: typeof SanatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-stream': {
      id: '/api/chat-stream'
      path: '/api/chat-stream'
      fullPath: '/api/chat-stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/chat': {
      id: '/workspace/chat'
      path: '/chat'
      fullPath: '/workspace/chat'
      preLoaderRoute: typeof WorkspaceChatRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/image': {
      id: '/workspace/image'
      path: '/image'
      fullPath: '/workspace/image'
      preLoaderRoute: typeof WorkspaceImageRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/library': {
      id: '/workspace/library'
      path: '/library'
      fullPath: '/workspace/library'
      preLoaderRoute: typeof WorkspaceLibraryRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/overview': {
      id: '/workspace/overview'
      path: '/overview'
      fullPath: '/workspace/overview'
      preLoaderRoute: typeof WorkspaceOverviewRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/research': {
      id: '/workspace/research'
      path: '/research'
      fullPath: '/workspace/research'
      preLoaderRoute: typeof WorkspaceResearchRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/sanatan': {
      id: '/workspace/sanatan'
      path: '/sanatan'
      fullPath: '/workspace/sanatan'
      preLoaderRoute: typeof WorkspaceSanatanRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/settings': {
      id: '/workspace/settings'
      path: '/settings'
      fullPath: '/workspace/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/video': {
      id: '/workspace/video'
      path: '/video'
      fullPath: '/workspace/video'
      preLoaderRoute: typeof WorkspaceVideoRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/voice': {
      id: '/workspace/voice'
      path: '/voice'
      fullPath: '/workspace/voice'
      preLoaderRoute: typeof WorkspaceVoiceRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/video-file': {
      id: '/api/public/video-file'
      path: '/api/public/video-file'
      fullPath: '/api/public/video-file'
      preLoaderRoute: typeof ApiPublicVideoFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkspaceRouteRouteChildren {
  WorkspaceChatRoute: typeof WorkspaceChatRoute
  WorkspaceImageRoute: typeof WorkspaceImageRoute
  WorkspaceLibraryRoute: typeof WorkspaceLibraryRoute
  WorkspaceOverviewRoute: typeof WorkspaceOverviewRoute
  WorkspaceResearchRoute: typeof WorkspaceResearchRoute
  WorkspaceSanatanRoute: typeof WorkspaceSanatanRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceVideoRoute: typeof WorkspaceVideoRoute
  WorkspaceVoiceRoute: typeof WorkspaceVoiceRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceChatRoute: WorkspaceChatRoute,
  WorkspaceImageRoute: WorkspaceImageRoute,
  WorkspaceLibraryRoute: WorkspaceLibraryRoute,
  WorkspaceOverviewRoute: WorkspaceOverviewRoute,
  WorkspaceResearchRoute: WorkspaceResearchRoute,
  WorkspaceSanatanRoute: WorkspaceSanatanRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceVideoRoute: WorkspaceVideoRoute,
  WorkspaceVoiceRoute: WorkspaceVoiceRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  LibraryRoute: LibraryRoute,
  PricingRoute: PricingRoute,
  ResponsibleAiRoute: ResponsibleAiRoute,
  SanatanRoute: SanatanRoute,
  SettingsRoute: SettingsRoute,
  ApiChatStreamRoute: ApiChatStreamRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiPublicVideoFileRoute: ApiPublicVideoFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
